import Cookies from "cookies";
import { nanoid } from "nanoid/async";
import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import { prisma } from "../server/db/client";
import { userIdCookieKey } from "../utils/constants";
import { trpc } from "../utils/trpc";

const Home: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = (
  props
) => {
  const urlCreateMutation = trpc.url.create.useMutation();

  const handleClick = () => {
    urlCreateMutation.mutate({ name: "text", url: "https://google.com" });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center p-4">
        Your user ID is {props.userId}
        <button className="btn" onClick={handleClick}>
          Add url
        </button>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<{
  userId: string;
}> = async ({ req, res }) => {
  if (req.cookies[userIdCookieKey]) {
    return { props: { userId: req.cookies[userIdCookieKey] } };
  }

  const userId = await nanoid();
  await prisma.user.create({ data: { id: userId } });

  const cookies = new Cookies(req, res);
  cookies.set(userIdCookieKey, userId, { httpOnly: true, expires: undefined });

  return { props: { userId } };
};

export default Home;
